### ISSUE TITLE
[Bug] Impossible to start the project

### ISSUE THREAD

**Issue by XStarlink** [creativetimofficial/ct-argon-design-system-pro-angular#1]
### Version
1.0.0
### Reproduction link
https://codepen.io/
### Operating System
MacOS Catalina
### Device
Macbook pro 2019 13`
### Browser & Version
Chrome latest
### Steps to reproduce
>> npm install
audited 16697 packages in 5.503s

21 packages are looking for funding
  run `npm fund` for details

found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

>> ng serve
Your global Angular CLI version (8.3.20) is greater than your local
version (8.3.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
10% building 4/4 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.01 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 531 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.37 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-01-03T16:32:42.194Z - Hash: 9ab1be39519bb19013eb - Time: 7877ms

ERROR in app/app.module.ts:1:32 - error TS2307: Cannot find module 'ngx-chips'.

1 import { TagInputModule } from "ngx-chips";
                                 ~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
### What is expected?
Project starting...
### What is actually happening?
Error Failed to compile.

---
### Solution

### Additional comments

<!-- generated by creative-tim-issues. DO NOT REMOVE -->

**Comment by chelaruc** [comment]
Hi, @QuentinCamboulives. Thank you for using our product and for pointing this to us. You can remove the import from the app.module.ts file. All the best, Ciprian
