### ISSUE TITLE
[Bug] Transition between mobile and desktop widths (responsive) stops desktop menu from working

### ISSUE THREAD

**Issue by Qara-Penimah** [creativetimofficial/ct-argon-design-system-pro-angular#4]
### Version
1.1.1
### Reproduction link
https://demos.creative-tim.com/argon-design-system-pro-angular/#/presentation
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Edge Version 85.0.564.51 (Official build) (64-bit) - Based on Chronium
### Steps to reproduce
1. Launch website maximised in desktop view
2. Hover over the menu options and see them expand
3. Shrink browser width to trigger responsive behaviour (mobile menu)
4. Click on hamburger and open mobile menu
5. Close mobile menu
6. Maximise browser window
7. Hover over the menu options to see them expand (They will not expand)
### What is expected?
On step 7 the drop-down menus are expected to expand but do not.
### What is actually happening?
The menus do not expand but show an arrow underneath the menu option.

---

**Comment by rarestoma** [comment]
Hi @Qara-Penimah,

Thank you for working with our products and for providing us this issue.

Please go to `src/assets/scss/bootstrap/_navbar.scss` and add, to the `.navbar-collapse`,` overflow: visible !important`
Please let me know if it works now.

Thank you,
Rares

**Comment by Qara-Penimah** [comment]
Is that a typo and should that be `overflow: visible`?

**Comment by rarestoma** [comment]
Hi @Qara-Penimah,

I updated the comment, you have to add `overflow: visible !important`.

Thank you,
Rares

**Comment by Qara-Penimah** [comment]
I ran a test today and this fix seems to have worked.

Apologies for taking so long to come back to you, I missed the notification and didn't realise you had commended 23 days ago.
